// Generated by Selenium IDE
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using Xunit;
public class SuiteTests : IDisposable {
  public IWebDriver driver {get; private set;}
  public IDictionary<String, Object> vars {get; private set;}
  public IJavaScriptExecutor js {get; private set;}
  public SuiteTests()
  {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<String, Object>();
  }
  public void Dispose()
  {
    driver.Quit();
  }
  [Fact]
  public void Shoppingcart() {
    driver.Navigate().GoToUrl("http://localhost:5041/");
    driver.Manage().Window.Size = new System.Drawing.Size(1382, 744);
    driver.FindElement(By.LinkText("Home")).Click();
    driver.FindElement(By.LinkText("Flowers")).Click();
    driver.FindElement(By.LinkText("Add to Cart")).Click();
    driver.FindElement(By.Id("Quantity")).SendKeys("1");
    driver.FindElement(By.Id("Quantity")).Click();
    driver.FindElement(By.Id("Quantity")).SendKeys("2");
    driver.FindElement(By.Id("Quantity")).Click();
    {
      var element = driver.FindElement(By.Id("Quantity"));
      Actions builder = new Actions(driver);
      builder.DoubleClick(element).Perform();
    }
    driver.FindElement(By.Id("Quantity")).SendKeys("3");
    driver.FindElement(By.Id("Quantity")).Click();
    driver.FindElement(By.Id("Quantity")).SendKeys("4");
    driver.FindElement(By.Id("Quantity")).Click();
    driver.FindElement(By.Id("Quantity")).SendKeys("5");
    driver.FindElement(By.Id("Quantity")).Click();
    driver.FindElement(By.Id("Quantity")).SendKeys("6");
    driver.FindElement(By.Id("Quantity")).Click();
    driver.FindElement(By.Id("Quantity")).SendKeys("600");
    driver.FindElement(By.Name("addtocart")).Click();
    driver.FindElement(By.LinkText("Flowers")).Click();
    driver.FindElement(By.CssSelector("tr:nth-child(4) a")).Click();
    driver.FindElement(By.Id("theFlower_SalePrice")).Click();
    driver.FindElement(By.CssSelector("tr:nth-child(3)")).Click();
    driver.FindElement(By.Id("Quantity")).SendKeys("87");
    driver.FindElement(By.Name("addtocart")).Click();
    driver.FindElement(By.CssSelector("tr:nth-child(2) a")).Click();
    driver.FindElement(By.LinkText("Flowers")).Click();
    driver.FindElement(By.CssSelector("tr:nth-child(5) a")).Click();
    driver.FindElement(By.CssSelector("tr:nth-child(3)")).Click();
    driver.FindElement(By.Id("Quantity")).SendKeys("9");
    driver.FindElement(By.Name("addtocart")).Click();
  }
}
